var watches= [
    {id:"1", imgsrc:"watch.jpg",title:"I7 Pro Max Smart Watch | Android & IOS | Blood Pressure Sensor | Heart Rate Sensor | IP67 Waterproof | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab " , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"2", imgsrc:"watch2.jpg",title:"Xiaomi | Mibro Air Smart Watch | Silicone Strap | Heart Rate Monitor | 12 Sports Mode | IP68 Waterproof | SmartWatch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"3", imgsrc:"watch3.jpg",title:"MC72 Pro Smartwatch | 44mm | Bluetooth Call | Body Temperature | ECG Blood Pressure | Heart Rate Monitor | Android IOS | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"4", imgsrc:"watch4.jpg",title:"HW21 Smartwatch | 42mm | IP68 Waterproof | Heart Rate Monitor | Fitness Band | Colorful Touch Screen | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"5", imgsrc:"watch5.jpg",title:" IWO | FK99 Smartwatch | Series 6 | Heart Rate Sensor | Pedometer | Bluetooth music | Push notifications | Smart Watch    ", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
    
    {id:"6", imgsrc:"watch6.jpg",title:"Xiaomi Mibro A1 | 1.28″ HD Display | 20 Sports Mode | Blood Oxygen Monitor | Heart Rate Sensor | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"7", imgsrc:"watch7.jpg",title:"Haylou GST | Silicone Strap | 22mm | Heart Rate Monitor | Blood Oxygen Monitor | Sleep Monitoring |", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"8", imgsrc:"watch8.jpg",title:"HX68 Smartwatch | Bluetooth Call | Android & IOS | Heart Rate Sensor | G Sensor | Sleep Monitor | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"9", imgsrc:"watch9.jpg",title:"HX68 Smartwatch | Bluetooth Call | Android & IOS | Heart Rate Sensor | G Sensor | Sleep Monitor", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"10", imgsrc:"watch10.jpg",title:"Haylou Smart Watch 2 | Silicone Strap | 44mm | Heart Rate Monitor | Blood Oxygen Monitor | IP68 Waterproof | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"11", imgsrc:"watch11.jpg",title:"Xiaomi | Mibro Air Smart Watch | Silicone Strap | Heart Rate Monitor | 12 Sports Mode | IP68 Waterproof | SmartWatch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},

    
    {id:"12", imgsrc:"watch11.jpg",title:"Xiaomi | Mibro Air Smart Watch | Silicone Strap | Heart Rate Monitor | 12 Sports Mode | IP68 Waterproof | SmartWatch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",}

    
  ]   